name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            host: linux
            platform: android
          - os: macos-latest
            host: darwin
            platform: android
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.host }}-${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: android/build/_drive
          key: corestore-${{ matrix.host }}
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - run: npm install
      - run: gh release download --repo holepunchto/bare-kit v1.0.0
        env:
          GH_TOKEN: ${{ github.token }}
      - run: unzip prebuilds.zip "android/bare-kit/*" -d prebuilds/
      - run: mv prebuilds/android/bare-kit app/libs/
      - run: gradle build
